function Hd = Chebyshev2_Bandpass_Filter(stop1, stop2, pass1, pass2)
%CHEBYSHEV2_BANDPASS_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 26-Nov-2020 16:56:08

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

%Fstop1 = 99;          % First Stopband Frequency
Fstop1 = stop1;          % First Stopband Frequency
%Fpass1 = 100;         % First Passband Frequency
Fpass1 = pass1;         % First Passband Frequency
%Fpass2 = 7999;        % Second Passband Frequency
Fpass2 = pass2;        % Second Passband Frequency
%Fstop2 = 8000;        % Second Stopband Frequency
Fstop2 = stop2;        % Second Stopband Frequency
Astop1 = 60;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 150;          % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
